name: Auto-close Dependabot Issues

on:
  pull_request:
    types: [closed]

jobs:
  autoclose:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.merged == true

    steps:
      - name: Close related issues
        uses: actions/github-script@v9
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
            });

            for (const issue of issues.data) {
              if (issue.title.toLowerCase().includes("dependabot")) {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: "closed",
                });
              }
            }
